name: kaggle_introvert_extrovert_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - xgboost
  - lightgbm
  - catboost
  - tqdm
  - plotly
  - ipykernel
  - optuna
  - pip
